package org.wemeet.portal.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static org.wemeet.portal.domain.AssertUtils.zonedDataTimeSameInstant;

public class BoardGameAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoardGameAllPropertiesEquals(BoardGame expected, BoardGame actual) {
        assertBoardGameAutoGeneratedPropertiesEquals(expected, actual);
        assertBoardGameAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoardGameAllUpdatablePropertiesEquals(BoardGame expected, BoardGame actual) {
        assertBoardGameUpdatableFieldsEquals(expected, actual);
        assertBoardGameUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoardGameAutoGeneratedPropertiesEquals(BoardGame expected, BoardGame actual) {
        assertThat(expected)
            .as("Verify BoardGame auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoardGameUpdatableFieldsEquals(BoardGame expected, BoardGame actual) {
        assertThat(expected)
            .as("Verify BoardGame relevant properties")
            .satisfies(e -> assertThat(e.getEnglishName()).as("check englishName").isEqualTo(actual.getEnglishName()))
            .satisfies(e -> assertThat(e.getChineseName()).as("check chineseName").isEqualTo(actual.getChineseName()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getYearPublished()).as("check yearPublished").isEqualTo(actual.getYearPublished()))
            .satisfies(e -> assertThat(e.getMinPlayers()).as("check minPlayers").isEqualTo(actual.getMinPlayers()))
            .satisfies(e -> assertThat(e.getMaxPlayers()).as("check maxPlayers").isEqualTo(actual.getMaxPlayers()))
            .satisfies(e -> assertThat(e.getPlayTimeMin()).as("check playTimeMin").isEqualTo(actual.getPlayTimeMin()))
            .satisfies(e -> assertThat(e.getPlayTimeMax()).as("check playTimeMax").isEqualTo(actual.getPlayTimeMax()))
            .satisfies(e -> assertThat(e.getMinAge()).as("check minAge").isEqualTo(actual.getMinAge()))
            .satisfies(e -> assertThat(e.getSuggestedAge()).as("check suggestedAge").isEqualTo(actual.getSuggestedAge()))
            .satisfies(e -> assertThat(e.getMechanics()).as("check mechanics").isEqualTo(actual.getMechanics()))
            .satisfies(e -> assertThat(e.getCategories()).as("check categories").isEqualTo(actual.getCategories()))
            .satisfies(e -> assertThat(e.getPublishers()).as("check publishers").isEqualTo(actual.getPublishers()))
            .satisfies(e -> assertThat(e.getRating()).as("check rating").isEqualTo(actual.getRating()))
            .satisfies(e -> assertThat(e.getRatingVotes()).as("check ratingVotes").isEqualTo(actual.getRatingVotes()))
            .satisfies(e -> assertThat(e.getComplexity()).as("check complexity").isEqualTo(actual.getComplexity()))
            .satisfies(e -> assertThat(e.getComplexityVotes()).as("check complexityVotes").isEqualTo(actual.getComplexityVotes()))
            .satisfies(e -> assertThat(e.getOfficialUrl()).as("check officialUrl").isEqualTo(actual.getOfficialUrl()))
            .satisfies(e -> assertThat(e.getBggUrl()).as("check bggUrl").isEqualTo(actual.getBggUrl()))
            .satisfies(e -> assertThat(e.getGstoneUrl()).as("check gstoneUrl").isEqualTo(actual.getGstoneUrl()))
            .satisfies(e -> assertThat(e.getThumbnailUrl()).as("check thumbnailUrl").isEqualTo(actual.getThumbnailUrl()))
            .satisfies(e -> assertThat(e.getLargeImageUrl()).as("check largeImageUrl").isEqualTo(actual.getLargeImageUrl()))
            .satisfies(e ->
                assertThat(e.getCreatedAt())
                    .as("check createdAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getCreatedAt())
            )
            .satisfies(e ->
                assertThat(e.getUpdatedAt())
                    .as("check updatedAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(actual.getUpdatedAt())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBoardGameUpdatableRelationshipsEquals(BoardGame expected, BoardGame actual) {
        // empty method
    }
}
