openapi: 3.0.3
info:
  title: Board Game API
  description: API for searching board games
  version: 1.0.0
servers:
  - url: http://localhost:8082/api/v1
tags:
  - name: Board Game
paths:
  /games/{gameId}:
    get:
      summary: Find game information by gameId
      operationId: getGameById
      tags:
        - Board Game
      parameters:
        - name: gameId
          in: path
          description: Id of the board game
          required: true
          schema:
            type: integer
        - name: includeExpansion
          in: query
          description: If response will include expansion game
          required: false
          schema:
            default: false
            type: boolean

      responses:
        '200':
          description: A board game information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'

  /games/query:
    get:
      summary: Find game list by its gameId
      operationId: getGameListByIds
      tags:
        - Board Game
      parameters:
        - name: gameIds
          in: query
          description: ID of games and separated by comma
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A board game information
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Game'

  /games/search:
    get:
      summary: Search for board games
      operationId: searchBoardGames
      tags:
        - Board Game
      parameters:
        - name: name
          in: query
          description: English or Chinese name of the game
          required: false
          schema:
            type: string
        - name: minPlayers
          in: query
          description: Minimum number of players
          required: false
          schema:
            type: integer
        - name: maxPlayers
          in: query
          description: Maximum number of players
          required: false
          schema:
            type: integer
        - name: category
          in: query
          description: Category of the game
          required: false
          schema:
            type: string
        - name: theme
          in: query
          description: Theme of the game
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A list of board games matching the criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Game'
components:
  schemas:
    GameQueryRequest:
      type: object
      properties:
        gameIds:
          type: array
          items:
            type: integer
    Game:
      type: object
      properties:
        id:
          type: string
        gameId:
          type: integer
        englishName:
          type: string
        chineseName:
          type: string
        playedCount:
          type: integer
          description: how many times of this game has been played
          default: 0
        totalTime:
          type: integer
        averageTimePerPlayer:
          type: integer
        primaryLanguage:
          type: string
        categories:
          type: array
          items:
            type: string
        themes:
          type: array
          items:
            type: string
        mode:
          type: string
        boxUrl:
          type: string
        coverUrl:
          type: string
        status:
          type: string
        difficulty:
          type: integer
        publishYear:
          type: integer
        minPlayers:
          type: integer
        maxPlayers:
          type: integer
        gameHotnessValue:
          type: integer
        wemeetRating:
          type: number
        gstoneRating:
          type: number
        relationInfo:
          type: array
          items:
            $ref: '#/components/schemas/RelationGame'

    RelationGame:
      type: object
      properties:
        is_mm:
          type: integer
          description: Indicates if it is mm.
        sub_category:
          type: string
          description: Sub category of the game.
        is_expansion:
          type: integer
          description: Indicates if it is an expansion.
        mod_type:
          type: integer
          description: Modification type.
        is_pg:
          type: integer
          description: Indicates if it is pg.
        box_url:
          type: string
          description: URL to the game box image.
        primary_language:
          type: string
          description: Primary language of the game.
        id:
          type: integer
          description: Unique identifier for the game.
        cover_url_s:
          type: string
          description: Small cover URL of the game.
        publish_year:
          type: integer
          description: Year of publication.
        status:
          type: integer
          description: Status of the game.
        expansion_type:
          type: integer
          description: Type of expansion.
        width_height:
          type: number
          format: double
          description: Width and height ratio.
        is_glight:
          type: integer
          description: Indicates if it is glight.
        cover_url:
          type: string
          description: Cover URL of the game.
        first_picture:
          type: object
          description: First picture object.
          properties:
            picture_url:
              type: string
              description: URL of the first picture.
            picture_url_s:
              type: string
            width_height:
              type: number
              format: double
        name:
          type: string
          description: Name of the game.
        game_hotness_value:
          type: number
          format: double
          description: Hotness value of the game.
        sales_mode_id:
          type: integer
          description: Sales mode ID.
        box_url_s:
          type: string
          description: Small box URL of the game.
        publish_month:
          type: integer
          description: Month of publication.
