openapi: 3.0.3
info:
  title: Board Game API
  description: API for searching board games
  version: 1.0.0
servers:
  - url: http://localhost:8082/api/v1
tags:
  - name: Board Game
paths:
  /games/{gameId}:
    get:
      summary: Find game information by gameId
      operationId: getGameById
      tags:
        - Board Game
      parameters:
        - name: gameId
          in: path
          description: Id of the board game
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A board game information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'

  /games/query:
    get:
      summary: Find game list by its gameId
      operationId: getGameListByIds
      tags:
        - Board Game
      parameters:
        - name: gameIds
          in: query
          description: ID of games and separated by comma
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A board game information
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Game'

  /games/search:
    get:
      summary: Search for board games
      operationId: searchBoardGames
      tags:
        - Board Game
      parameters:
        - name: name
          in: query
          description: English or Chinese name of the game
          required: false
          schema:
            type: string
        - name: minPlayers
          in: query
          description: Minimum number of players
          required: false
          schema:
            type: integer
        - name: maxPlayers
          in: query
          description: Maximum number of players
          required: false
          schema:
            type: integer
        - name: category
          in: query
          description: Category of the game
          required: false
          schema:
            type: string
        - name: theme
          in: query
          description: Theme of the game
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A list of board games matching the criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Game'
components:
  schemas:
    GameQueryRequest:
      type: object
      properties:
        gameIds:
          type: array
          items:
            type: integer
    Game:
      type: object
      properties:
        id:
          type: string
        gameId:
          type: integer
        englishName:
          type: string
        chineseName:
          type: string
        totalTime:
          type: integer
        averageTimePerPlayer:
          type: integer
        primaryLanguage:
          type: string
        categories:
          type: array
          items:
            type: string
        themes:
          type: array
          items:
            type: string
        mode:
          type: string
        boxUrl:
          type: string
        coverUrl:
          type: string
        status:
          type: string
        difficulty:
          type: integer
        publishYear:
          type: integer
        minPlayers:
          type: integer
        maxPlayers:
          type: integer
        gameHotnessValue:
          type: integer
        wemeetRating:
          type: number
        gstoneRating:
          type: number
